"""initial_maritime_schema

Revision ID: a741f3e0ae0d
Revises: 
Create Date: 2026-09-12 03:12:18.690149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a741f3e0ae0d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = set(inspector.get_table_names())

    orig_create_table = op.create_table
    def safe_create_table(name, *args, **kwargs):
        if name not in existing_tables:
            res = orig_create_table(name, *args, **kwargs)
            existing_tables.add(name)
            return res
    op.create_table = safe_create_table

    orig_create_index = op.create_index
    def safe_create_index(name, table_name, *args, **kwargs):
        try:
            indexes = [idx['name'] for idx in inspector.get_indexes(table_name)]
            if name in indexes:
                return
        except Exception:
            pass
        return orig_create_index(name, table_name, *args, **kwargs)
    op.create_index = safe_create_index

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_sync_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feed_name', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('records_synced', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cargo_plans',
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('cargo_type', sa.String(), nullable=False),
    sa.Column('cargo_quantity', sa.Float(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('destination_port', sa.String(), nullable=False),
    sa.Column('required_arrival_date', sa.String(), nullable=False),
    sa.Column('max_budget', sa.Float(), nullable=False),
    sa.Column('preferred_vessel_class', sa.String(), nullable=True),
    sa.Column('supplier_price_per_tonne', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_table('charter_bookings',
    sa.Column('booking_id', sa.String(), nullable=False),
    sa.Column('cargo_plan_id', sa.String(), nullable=True),
    sa.Column('vessel_id', sa.String(), nullable=False),
    sa.Column('origin_port', sa.String(), nullable=False),
    sa.Column('destination_port', sa.String(), nullable=False),
    sa.Column('selected_route_type', sa.String(), nullable=False),
    sa.Column('selected_berth_id', sa.String(), nullable=True),
    sa.Column('planned_departure', sa.String(), nullable=False),
    sa.Column('planned_arrival', sa.String(), nullable=False),
    sa.Column('berthing_start', sa.String(), nullable=True),
    sa.Column('berthing_end', sa.String(), nullable=True),
    sa.Column('cargo_quantity', sa.Float(), nullable=False),
    sa.Column('cargo_type', sa.String(), nullable=False),
    sa.Column('estimated_total_cost', sa.Float(), nullable=False),
    sa.Column('cost_per_ton', sa.Float(), nullable=False),
    sa.Column('booking_status', sa.String(), nullable=False),
    sa.Column('risk_status', sa.String(), nullable=False),
    sa.Column('data_status', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_index('idx_charter_bookings_status', 'charter_bookings', ['booking_status'], unique=False)
    op.create_table('commodity_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('commodity', sa.String(), nullable=False),
    sa.Column('market', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('price_date', sa.String(), nullable=True),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.Column('data_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fleet_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.String(), nullable=True),
    sa.Column('plan_id', sa.String(), nullable=True),
    sa.Column('vessel_id', sa.String(), nullable=False),
    sa.Column('assignment_date', sa.String(), nullable=False),
    sa.Column('laycan_start', sa.String(), nullable=False),
    sa.Column('laycan_end', sa.String(), nullable=False),
    sa.Column('allocated_cargo_qty', sa.Float(), nullable=False),
    sa.Column('utilization_rate', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fleet_assignments_vessel_date', 'fleet_assignments', ['vessel_id', 'assignment_date'], unique=False)
    op.create_table('freight_forecasts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.String(), nullable=True),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('cargo_type', sa.String(), nullable=False),
    sa.Column('vessel_class', sa.String(), nullable=True),
    sa.Column('predicted_rate', sa.Float(), nullable=False),
    sa.Column('forecast_direction', sa.String(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('mae', sa.Float(), nullable=True),
    sa.Column('rmse', sa.Float(), nullable=True),
    sa.Column('mape', sa.Float(), nullable=True),
    sa.Column('data_status', sa.String(), nullable=False),
    sa.Column('limitations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('freight_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('cargo_type', sa.String(), nullable=False),
    sa.Column('vessel_class', sa.String(), nullable=False),
    sa.Column('freight_rate', sa.Float(), nullable=False),
    sa.Column('bdi', sa.Float(), nullable=True),
    sa.Column('bunker_price', sa.Float(), nullable=True),
    sa.Column('port_congestion', sa.Float(), nullable=True),
    sa.Column('vessel_availability', sa.Float(), nullable=True),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.Column('data_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('freight_rates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('origin', sa.String(), nullable=True),
    sa.Column('destination', sa.String(), nullable=True),
    sa.Column('vessel_class', sa.String(), nullable=True),
    sa.Column('rate_usd_per_ton', sa.Float(), nullable=True),
    sa.Column('rate_date', sa.String(), nullable=True),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.Column('data_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fuel_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fuel_type', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('price_date', sa.String(), nullable=True),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.Column('data_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('optimization_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.String(), nullable=True),
    sa.Column('recommended_plan', sa.String(), nullable=False),
    sa.Column('estimated_total_cost', sa.Float(), nullable=False),
    sa.Column('estimated_cost_per_tonne', sa.Float(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('reasons', sa.Text(), nullable=False),
    sa.Column('warnings', sa.Text(), nullable=True),
    sa.Column('alternatives', sa.Text(), nullable=True),
    sa.Column('data_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ports',
    sa.Column('port_id', sa.String(), nullable=False),
    sa.Column('port_name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('draft_meters', sa.Float(), nullable=True),
    sa.Column('max_dwt', sa.Float(), nullable=True),
    sa.Column('avg_waiting_days', sa.Float(), nullable=True),
    sa.Column('congestion_index', sa.Float(), nullable=True),
    sa.Column('operational_status', sa.String(), nullable=True),
    sa.Column('last_updated', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('port_id')
    )
    op.create_table('route_alerts',
    sa.Column('alert_id', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('area', sa.String(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=True),
    sa.Column('end_time', sa.String(), nullable=True),
    sa.Column('affected_route', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('last_checked', sa.String(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('data_status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_index('idx_route_alerts_route_sev', 'route_alerts', ['affected_route', 'severity'], unique=False)
    op.create_table('route_corridors',
    sa.Column('corridor_id', sa.String(), nullable=False),
    sa.Column('origin_port', sa.String(), nullable=False),
    sa.Column('origin_country', sa.String(), nullable=False),
    sa.Column('origin_lat', sa.Float(), nullable=False),
    sa.Column('origin_lng', sa.Float(), nullable=False),
    sa.Column('destination_port', sa.String(), nullable=False),
    sa.Column('destination_country', sa.String(), nullable=True),
    sa.Column('destination_lat', sa.Float(), nullable=False),
    sa.Column('destination_lng', sa.Float(), nullable=False),
    sa.Column('cargo_type', sa.String(), nullable=False),
    sa.Column('typical_vessel_classes', sa.String(), nullable=False),
    sa.Column('approximate_corridor', sa.String(), nullable=False),
    sa.Column('waypoints', sa.Text(), nullable=False),
    sa.Column('estimated_distance_nm', sa.Integer(), nullable=False),
    sa.Column('typical_sailing_days', sa.Float(), nullable=False),
    sa.Column('seasonal_risk_areas', sa.Text(), nullable=True),
    sa.Column('port_restrictions', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(), nullable=False),
    sa.Column('data_confidence', sa.Float(), nullable=False),
    sa.Column('is_verified_nautical', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('corridor_id')
    )
    op.create_table('route_options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('option_type', sa.String(), nullable=False),
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('waypoints', sa.Text(), nullable=False),
    sa.Column('distance_nm', sa.Integer(), nullable=False),
    sa.Column('sailing_days', sa.Float(), nullable=False),
    sa.Column('eta', sa.String(), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.Column('cost_per_ton_usd', sa.Float(), nullable=False),
    sa.Column('fuel_cost_usd', sa.Float(), nullable=False),
    sa.Column('port_charges_usd', sa.Float(), nullable=False),
    sa.Column('transit_charges_usd', sa.Float(), nullable=False),
    sa.Column('demurrage_risk_usd', sa.Float(), nullable=False),
    sa.Column('operating_cost_usd', sa.Float(), nullable=False),
    sa.Column('cost_savings_usd', sa.Float(), nullable=True),
    sa.Column('cost_drivers', sa.Text(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('weather_impact', sa.Text(), nullable=True),
    sa.Column('tradeoff_explanation', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(), nullable=False),
    sa.Column('data_confidence', sa.Float(), nullable=False),
    sa.Column('data_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vessel_options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.String(), nullable=True),
    sa.Column('vessel_id', sa.String(), nullable=False),
    sa.Column('vessel_name', sa.String(), nullable=False),
    sa.Column('vessel_class', sa.String(), nullable=False),
    sa.Column('capacity_dwt', sa.Float(), nullable=False),
    sa.Column('draft_meters', sa.Float(), nullable=True),
    sa.Column('suitability_status', sa.String(), nullable=False),
    sa.Column('suitability_score', sa.Float(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('estimated_voyage_days', sa.Float(), nullable=True),
    sa.Column('estimated_freight_cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vessels',
    sa.Column('vessel_id', sa.String(), nullable=False),
    sa.Column('imo', sa.String(), nullable=True),
    sa.Column('mmsi', sa.String(), nullable=True),
    sa.Column('vessel_name', sa.String(), nullable=False),
    sa.Column('vessel_type', sa.String(), nullable=True),
    sa.Column('dwt', sa.Float(), nullable=True),
    sa.Column('built_year', sa.Integer(), nullable=True),
    sa.Column('charter_rate_per_day', sa.Float(), nullable=True),
    sa.Column('fuel_consumption', sa.Float(), nullable=True),
    sa.Column('availability', sa.String(), nullable=True),
    sa.Column('current_route', sa.String(), nullable=True),
    sa.Column('port_compatibility', sa.String(), nullable=True),
    sa.Column('last_updated', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('vessel_id')
    )
    op.create_table('weather_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('wave_height_meters', sa.Float(), nullable=True),
    sa.Column('wind_speed_knots', sa.Float(), nullable=True),
    sa.Column('ocean_current_knots', sa.Float(), nullable=True),
    sa.Column('weather_condition', sa.String(), nullable=True),
    sa.Column('weather_risk', sa.String(), nullable=True),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.Column('data_status', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('port_terminals',
    sa.Column('terminal_id', sa.String(), nullable=False),
    sa.Column('port_id', sa.String(), nullable=False),
    sa.Column('terminal_name', sa.String(), nullable=False),
    sa.Column('cargo_specialization', sa.String(), nullable=False),
    sa.Column('max_draft', sa.Float(), nullable=False),
    sa.Column('max_dwt', sa.Float(), nullable=False),
    sa.Column('max_loa', sa.Float(), nullable=True),
    sa.Column('max_beam', sa.Float(), nullable=True),
    sa.Column('loading_rate_tpd', sa.Float(), nullable=True),
    sa.Column('unloading_rate_tpd', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['port_id'], ['ports.port_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('terminal_id')
    )
    op.create_table('rescheduling_options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.String(), nullable=False),
    sa.Column('option_type', sa.String(), nullable=False),
    sa.Column('proposed_port', sa.String(), nullable=True),
    sa.Column('proposed_vessel_id', sa.String(), nullable=True),
    sa.Column('proposed_arrival_date', sa.String(), nullable=True),
    sa.Column('proposed_berth_id', sa.String(), nullable=True),
    sa.Column('additional_cost_usd', sa.Float(), nullable=True),
    sa.Column('cost_variance_pct', sa.Float(), nullable=True),
    sa.Column('delay_days_saved', sa.Float(), nullable=True),
    sa.Column('feasibility_score', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['charter_bookings.booking_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vessel_positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vessel_id', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('speed_knots', sa.Float(), nullable=True),
    sa.Column('course_degrees', sa.Float(), nullable=True),
    sa.Column('heading_degrees', sa.Float(), nullable=True),
    sa.Column('draught_meters', sa.Float(), nullable=True),
    sa.Column('destination', sa.String(), nullable=True),
    sa.Column('eta', sa.String(), nullable=True),
    sa.Column('navigation_status', sa.String(), nullable=True),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.Column('data_status', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.vessel_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('berths',
    sa.Column('berth_id', sa.String(), nullable=False),
    sa.Column('terminal_id', sa.String(), nullable=True),
    sa.Column('port_id', sa.String(), nullable=False),
    sa.Column('berth_name', sa.String(), nullable=False),
    sa.Column('length_meters', sa.Float(), nullable=False),
    sa.Column('draft_meters', sa.Float(), nullable=False),
    sa.Column('max_dwt', sa.Float(), nullable=False),
    sa.Column('equipment', sa.Text(), nullable=True),
    sa.Column('operating_hours', sa.String(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['port_id'], ['ports.port_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['terminal_id'], ['port_terminals.terminal_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('berth_id')
    )
    op.create_table('berth_bookings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.String(), nullable=True),
    sa.Column('port_id', sa.String(), nullable=False),
    sa.Column('berth_id', sa.String(), nullable=False),
    sa.Column('vessel_id', sa.String(), nullable=False),
    sa.Column('arrival_time', sa.String(), nullable=False),
    sa.Column('berthing_start', sa.String(), nullable=False),
    sa.Column('berthing_end', sa.String(), nullable=False),
    sa.Column('departure_time', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('buffer_hours', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['berth_id'], ['berths.berth_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['port_id'], ['ports.port_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_berth_bookings_berth_window', 'berth_bookings', ['berth_id', 'arrival_time', 'departure_time'], unique=False)
    op.create_index('idx_berth_bookings_port_arrival', 'berth_bookings', ['port_id', 'arrival_time'], unique=False)
    # ### end Alembic commands ###
    op.create_table = orig_create_table
    op.create_index = orig_create_index


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_berth_bookings_port_arrival', table_name='berth_bookings')
    op.drop_index('idx_berth_bookings_berth_window', table_name='berth_bookings')
    op.drop_table('berth_bookings')
    op.drop_table('berths')
    op.drop_table('vessel_positions')
    op.drop_table('rescheduling_options')
    op.drop_table('port_terminals')
    op.drop_table('weather_observations')
    op.drop_table('vessels')
    op.drop_table('vessel_options')
    op.drop_table('route_options')
    op.drop_table('route_corridors')
    op.drop_index('idx_route_alerts_route_sev', table_name='route_alerts')
    op.drop_table('route_alerts')
    op.drop_table('ports')
    op.drop_table('optimization_runs')
    op.drop_table('fuel_prices')
    op.drop_table('freight_rates')
    op.drop_table('freight_observations')
    op.drop_table('freight_forecasts')
    op.drop_index('idx_fleet_assignments_vessel_date', table_name='fleet_assignments')
    op.drop_table('fleet_assignments')
    op.drop_table('commodity_prices')
    op.drop_index('idx_charter_bookings_status', table_name='charter_bookings')
    op.drop_table('charter_bookings')
    op.drop_table('cargo_plans')
    op.drop_table('api_sync_logs')
    # ### end Alembic commands ###
